### ISSUE TITLE
App crash after logout, login with new user and then send a message

### ISSUE THREAD

**Issue by devashishmamgain** [AppLozic/Applozic-iOS-SDK#32]
2015-09-29 14:57:06.849 ChatApp[1609:70788] Registration response from server:<ALRegistrationResponse: 0x7fd3fb65da60>
2015-09-29 14:57:06.872 ChatApp[1609:70788] /Users/devashish/Library/Developer/CoreSimulator/Devices/12124CF8-F5A5-482E-BB17-787B8DC0955F/data/Containers/Data/Application/23AE4E40-4BBF-4A97-8255-19E496104248/Documents
2015-09-29 14:57:06.874 ChatApp[1609:70788] the url,https://applozic.appspot.com/rest/ws/mobicomkit/v1/message/list
2015-09-29 14:57:06.876 ChatApp[1609:70788] Basic string...Basic cmFuZG9tOmFncHpmbUZ3Y0d4dmVtbGpjaVlMRWdaVGRWVnpaWElZZ0lDQWdQVHprZ2dNQ3hJR1JHVjJhV05sR0lDQWdJQ0FnSUFLREE=
2015-09-29 14:57:18.758 ChatApp[1609:70788] 0
2015-09-29 14:57:18.759 ChatApp[1609:70788] 0
2015-09-29 14:57:22.100 ChatApp[1609:70788] message not in DB new insertion.
2015-09-29 14:57:22.110 ChatApp[1609:70788] Basic string...Basic cmFuZG9tOmFncHpmbUZ3Y0d4dmVtbGpjaVlMRWdaVGRWVnpaWElZZ0lDQWdQVHprZ2dNQ3hJR1JHVjJhV05sR0lDQWdJQ0FnSUFLREE=
2015-09-29 14:57:22.694 ChatApp[1609:70788] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayI objectAtIndex:]: index 1 beyond bounds [0 .. 0]'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010163dc65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000100f1abb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010153417e -[__NSArrayI objectAtIndex:] + 190
	3   ChatApp                             0x0000000100958b4a __48+[ALMessageService sendMessages:withCompletion:]_block_invoke + 682
	4   ChatApp                             0x000000010091f776 __65+[ALResponseHandler processRequest:andTag:WithCompletionHandler:]_block_invoke + 1334
	5   CFNetwork                           0x0000000103e44c85 __67+[NSURLConnection sendAsynchronousRequest:queue:completionHandler:]_block_invoke_2 + 155
	6   Foundation                          0x0000000100b5357f __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	7   Foundation                          0x0000000100a940b2 -[NSBlockOperation main] + 98
	8   Foundation                          0x0000000100a76774 -[__NSOperationInternal _start:] + 645
	9   Foundation                          0x0000000100a76383 __NSOQSchedule_f + 184
	10  libdispatch.dylib                   0x0000000104649614 _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x0000000104631a1c _dispatch_main_queue_callback_4CF + 1664
	12  CoreFoundation                      0x00000001015a51f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	13  CoreFoundation                      0x0000000101566dcb __CFRunLoopRun + 2043
	14  CoreFoundation                      0x0000000101566366 CFRunLoopRunSpecific + 470
	15  GraphicsServices                    0x0000000107001a3e GSEventRunModal + 161
	16  UIKit                               0x0000000102611900 UIApplicationMain + 1282
	17  ChatApp                             0x000000010094af9f main + 111
	18  libdyld.dylib                       0x000000010467d145 start + 1
	19  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by Divjyot** [comment]
Printing description of statusStr:
<html>
<head>
<title>Error</title>
</head>
<body>
<h1>The resource did not process correctly</h1>
<pre>
java.lang.NullPointerException
	at net.mobitexter.modules.sms.SmsService.getContactNumbers(SmsService.java:275)
	at net.mobitexter.modules.sms.SmsCrudService.createSms(SmsCrudService.java:226)
	at net.mobitexter.modules.sms.SmsCrudService.create(SmsCrudService.java:204)
	at net.mobitexter.modules.sms.SmsCrudService.create(SmsCrudService.java:124)
	at net.mobitexter.modules.sms.SmsCrudService.create(SmsCrudService.java:40)
	at net.mobitexter.modules.ws.message.MessageWS.sendMessage(MessageWS.java:174)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:44)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:708)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at net.mobitexter.filter.PersistenceManagerFilter.doFilter(PersistenceManagerFilter.java:39)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at net.mobitexter.modules.ws.RestAuthenticationFilter.doFilter(RestAuthenticationFilter.java:139)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at net.mobitexter.filter.CharsetFilter.doFilter(CharsetFilter.java:35)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at net.mobitexter.filter.SimpleCORSFilter.doFilter(SimpleCORSFilter.java:29)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:230)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
	at java.lang.Thread.run(Thread.java:745)
</pre></body>
</html>


The above is reponse of statusStr which have Processing errors. DUE TO

**Comment by Divjyot** [comment]
Printing description of statusStr:
<html>
<head>
<title>Error</title>
</head>
<body>
<h1>The resource did not process correctly</h1>
<pre>
java.lang.NullPointerException
	at net.mobitexter.modules.sms.SmsService.getContactNumbers(SmsService.java:275)
	at net.mobitexter.modules.sms.SmsCrudService.createSms(SmsCrudService.java:226)
	at net.mobitexter.modules.sms.SmsCrudService.create(SmsCrudService.java:204)
	at net.mobitexter.modules.sms.SmsCrudService.create(SmsCrudService.java:124)
	at net.mobitexter.modules.sms.SmsCrudService.create(SmsCrudService.java:40)
	at net.mobitexter.modules.ws.message.MessageWS.sendMessage(MessageWS.java:174)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:44)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:708)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at net.mobitexter.filter.PersistenceManagerFilter.doFilter(PersistenceManagerFilter.java:39)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at net.mobitexter.modules.ws.RestAuthenticationFilter.doFilter(RestAuthenticationFilter.java:139)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at net.mobitexter.filter.CharsetFilter.doFilter(CharsetFilter.java:35)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at net.mobitexter.filter.SimpleCORSFilter.doFilter(SimpleCORSFilter.java:29)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:230)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
	at java.lang.Thread.run(Thread.java:745)
</pre></body>
</html>


The above is response of statusStr which have Processing errors.
Response index 1 is not available and yet its called therefore causing exception
